modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "infodump"
version = "${version}"
displayName = "InfoDump"
authors = "fabbe50"
description = '''
Dump information about the game.
'''
#logoFile = ""

[[dependencies.infodump]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.infodump]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.infodump]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "infodump.mixins.json"
